### PR TITLE
Chair Election 2023 ballot computed using OpenSTV

### PR DESCRIPTION
**Pull request by csarven**
Based on procedure: https://github.com/solid/specification/discussions/582 . Follows https://lists.w3.org/Archives/Public/public-solid/2023Dec/0016.html . Data from https://github.com/w3c-cg/solid/pull/11

To reproduce:

`runElection.py -s 3 -r TextReport MeekSTV ballots-anonymised.blt`

For anyone comparing the results in this PR with their computation, please do a text `diff` (or equivalent).

---

@ianbjacobs @dontcallmedom , once this PR is merged, you can use https://github.com/w3c-cg/solid/blob/main/elections/2023/results-anonymised.txt to de-anonymise and announce the elected chairs in public-solid@w3.org . I can inform you over email as well.

### CODE REVIEW

**Review by elf-pavlik — APPROVED** [review]
confirming same results as in my OpenSTV run #12

**Comment by megoth** [comment]
I've run the script locally and can confirm that it matches this as well

**Review by megoth — APPROVED** [review]
I've run the script locally and can confirm that it matches this as well

**Comment by pchampin** [comment]
I also get the same results by running the script locally.

**Review by ewingson — APPROVED** [review]
as said yesterday, #me can approve as well...

**Comment by csarven** [comment]
Thank you all for contributing with your reviews and confirming the results. Merging as all computations match and there are no objections.

@ianbjacobs @dontcallmedom , https://github.com/w3c-cg/solid/blob/main/elections/2023/results-anonymised.txt  contains the computed results. I would greatly appreciate it if you could PR the elected candidates (with real names) at `https://github.com/w3c-cg/solid/blob/main/elections/2023/elected-candidates.txt` (one per line would suffice) in addition to your announcement at public-solid@w3.org . We will also merge this PR as is. Thank you.

**Pull request merged**
