### PR TITLE
OpenSTV results

### PR DESCRIPTION
**Pull request by elf-pavlik**
Using data from #11 
And code from: https://github.com/Conservatory/openstv

```bash
python2 runElection.py -r TextReport MeekSTV ballots-anonymised.blt
```

### CODE REVIEW

**Comment by michielbdejong** [comment]
> Winners are Candidate 2, Candidate 4, and Candidate 5.

And who is who in this numbering?

**Comment by elf-pavlik** [comment]
This goes back to W3C and they will announce the results.

**Comment by VirginiaBalseiro** [comment]
> And who is who in this numbering?

We'll send this back to W3C Team and they will give us the names.

**Comment by csarven** [comment]
@elf-pavlik , as we previously discussed in solid/specification chat, can we please review the PR that I suggested we should follow up on regarding reproducing: https://github.com/w3c-cg/solid/pull/13 ? You can confirm there if matches your results or not - I think it does. Please close this PR if no objection.

**Pull request closed without merging**
